import { defineConfig } from 'wxt';

export default defineConfig({
  manifestVersion: 3,
  modules: ['@wxt-dev/module-svelte'],
  manifest: ({ browser }) => ({
    // Both come from public/_locales, generated by `bun run locales`.
    name: '__MSG_extName__',
    description: '__MSG_extDescription__',
    default_locale: 'en',
    // version is intentionally absent: WXT takes it from package.json, which
    // keeps a single source of truth. The popup reads it back from the manifest.
    // `activeTab` is what makes the per-site pause switch possible: it hands the
    // popup the current tab's URL, and only because the user just clicked the
    // extension icon. It grants nothing at rest and shows no install warning.
    permissions: ['storage', 'activeTab'],
    host_permissions: ['https://open.er-api.com/*'],
    icons: {
      16: 'icons/icon-16.png',
      32: 'icons/icon-32.png',
      48: 'icons/icon-48.png',
      128: 'icons/icon-128.png',
    },
    // The tooltip on the toolbar icon. Without this it inherits the popup's
    // <title>, which is untranslated English on every locale.
    action: { default_title: '__MSG_extName__' },
    ...(browser === 'firefox' && {
      browser_specific_settings: {
        gecko: {
          id: 'pricehover@klnuno',
          strict_min_version: '109.0',
          data_collection_permissions: {
            required: ['none'],
            optional: [],
          },
        },
      },
    }),
  }),
});
