import { defineConfig } from 'wxt';

export default defineConfig({
  manifestVersion: 3,
  modules: ['@wxt-dev/module-svelte'],
  // The sources zip goes to AMO reviewers and is attached to the GitHub
  // release. It is built from the working tree, not from git, so it happily
  // packs things git was told to ignore. `docs/` is the private store-listing
  // copy; `screenshots/` is 820 KB of images a reviewer has no use for.
  zip: {
    excludeSources: ['docs/**', 'screenshots/**'],
  },
  manifest: ({ browser }) => ({
    // Both come from public/_locales, generated by `bun run locales`.
    name: '__MSG_extName__',
    description: '__MSG_extDescription__',
    default_locale: 'en',
    // version is intentionally absent: WXT takes it from package.json, which
    // keeps a single source of truth. The popup reads it back from the manifest.
    // No `activeTab`. It looks free, and it is the reason the extension spent
    // three versions doing nothing until its icon was clicked: an extension
    // that asks for it is an extension whose access is granted per click, and
    // both browsers hand it that model in their site-access UI. The declared
    // content script then waits for a click it should never have needed.
    // v1.2.4 asked for `storage` alone and ran everywhere; this is that.
    permissions: ['storage'],
    // One host, and no `<all_urls>` here on purpose. Page access comes from the
    // content script's own `matches`, which has read `<all_urls>` since 1.0.0
    // and is granted at install in both browsers. Repeating it here would grant
    // nothing further and warn about nothing further; it would only make the
    // manifest louder than the extension.
    host_permissions: ['https://open.er-api.com/*'],
    // Optional, and off until asked for. Crypto waits for the switch in the
    // options page. `<all_urls>` is here so it can be *re-requested*: a profile
    // that once set site access to "on click" withholds the content script's
    // origins from every later build, and the settings page needs something
    // legal to ask for to hand them back. Declaring the capability is not using
    // it: nothing is requested, and nothing is contacted, for a profile that
    // never opts in. That is what keeps "the extension contacts exactly one
    // host" true, in PRIVACY.md, in the README and in the Firefox declaration
    // below.
    optional_host_permissions: ['<all_urls>', 'https://api.coingecko.com/*'],
    icons: {
      16: 'icons/icon-16.png',
      32: 'icons/icon-32.png',
      48: 'icons/icon-48.png',
      128: 'icons/icon-128.png',
    },
    // The tooltip on the toolbar icon. Without this it inherits the popup's
    // <title>, which is untranslated English on every locale.
    action: { default_title: '__MSG_extName__' },
    ...(browser === 'firefox' && {
      browser_specific_settings: {
        gecko: {
          id: 'pricehover@klnuno',
          // 127, not 109. Firefox shipped MV3 in 109, but until 127 it treated
          // host permissions and <all_urls> content-script matches as optional:
          // nothing injected and no rate fetch until the user went looking for
          // the unified extensions button. An install that silently does
          // nothing is worse than no install.
          strict_min_version: '127.0',
          data_collection_permissions: {
            required: ['none'],
            optional: [],
          },
        },
      },
    }),
  }),
});
