import { defineConfig } from 'wxt';

export default defineConfig({
  manifestVersion: 3,
  modules: ['@wxt-dev/module-svelte'],
  // The sources zip goes to AMO reviewers and is attached to the GitHub
  // release. It is built from the working tree, not from git, so it happily
  // packs things git was told to ignore. `docs/` is the private store-listing
  // copy; `screenshots/` is 820 KB of images a reviewer has no use for.
  zip: {
    excludeSources: ['docs/**', 'screenshots/**'],
  },
  manifest: ({ browser }) => ({
    // Both come from public/_locales, generated by `bun run locales`.
    name: '__MSG_extName__',
    description: '__MSG_extDescription__',
    default_locale: 'en',
    // version is intentionally absent: WXT takes it from package.json, which
    // keeps a single source of truth. The popup reads it back from the manifest.
    // `activeTab` is what makes the per-site pause switch possible: it hands the
    // popup the current tab's URL, and only because the user just clicked the
    // extension icon. It grants nothing at rest and shows no install warning.
    permissions: ['storage', 'activeTab'],
    host_permissions: ['https://open.er-api.com/*'],
    icons: {
      16: 'icons/icon-16.png',
      32: 'icons/icon-32.png',
      48: 'icons/icon-48.png',
      128: 'icons/icon-128.png',
    },
    // The tooltip on the toolbar icon. Without this it inherits the popup's
    // <title>, which is untranslated English on every locale.
    action: { default_title: '__MSG_extName__' },
    ...(browser === 'firefox' && {
      browser_specific_settings: {
        gecko: {
          id: 'pricehover@klnuno',
          // 127, not 109. Firefox shipped MV3 in 109, but until 127 it treated
          // host permissions and <all_urls> content-script matches as optional:
          // nothing injected and no rate fetch until the user went looking for
          // the unified extensions button. An install that silently does
          // nothing is worse than no install.
          strict_min_version: '127.0',
          data_collection_permissions: {
            required: ['none'],
            optional: [],
          },
        },
      },
    }),
  }),
});
