/**
 * Downloads every flag used by CURRENCIES and writes src/flags.ts as inline
 * data URIs. Run it again only when a currency is added or removed:
 *
 *   bun run flags
 *
 * The extension must never fetch flags at runtime: a request made from the
 * content script would leak the visited page's origin to a third party.
 *
 * Flag artwork comes from flagcdn.com, which publishes it in the public domain.
 */
import { writeFileSync } from 'fs';
import { CURRENCIES, flagToCountryCode } from '../src/currencies';

// WebP at 40px wide: 2x the 20x15 CSS box, so it stays sharp on hidpi,
// and roughly a quarter the bytes of the equivalent PNG.
const SIZE = 'w40';

const codes = [...new Set(CURRENCIES.map((c) => flagToCountryCode(c.flag)))].sort();
const entries: string[] = [];
let total = 0;

for (const cc of codes) {
  const res = await fetch(`https://flagcdn.com/${SIZE}/${cc}.webp`);
  if (!res.ok) throw new Error(`${cc}: HTTP ${res.status}`);

  const image = Buffer.from(await res.arrayBuffer());
  total += image.byteLength;
  entries.push(`  ${cc}: 'data:image/webp;base64,${image.toString('base64')}',`);
  console.log(`✓ ${cc} (${image.byteLength} bytes)`);
}

const out = `// Generated by scripts/gen-flags.ts — do not edit by hand.
// Flag artwork from flagcdn.com (public domain), inlined so the extension makes
// no third-party request at runtime.

export const FLAG_DATA_URI: Record<string, string> = {
${entries.join('\n')}
};

/** Data URI for a country code, or '' when the flag is missing. */
export function flagImage(countryCode: string): string {
  return FLAG_DATA_URI[countryCode] ?? '';
}
`;

writeFileSync('src/flags.ts', out);
console.log(`\n${codes.length} flags, ${(total / 1024).toFixed(1)} kB raw → src/flags.ts`);
